# Generated by Django 4.1.7 on 2023-03-16 18:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_name', models.CharField(max_length=32)),
                ('plant_photo', models.ImageField(blank=True, upload_to='')),
                ('plant_care_humidity', models.IntegerField(blank=True, null=True)),
                ('plant_care_light', models.IntegerField(blank=True, null=True)),
                ('plant_care_minerals', models.FloatField(blank=True, null=True)),
                ('plant_care_ph', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pot_name', models.CharField(max_length=32)),
                ('plants_pot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plants', related_query_name='plant', to='pyflora_app.plant')),
            ],
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stats_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('humidity_status', models.IntegerField()),
                ('lux_status', models.IntegerField()),
                ('minerals', models.FloatField()),
                ('ph', models.IntegerField(null=True)),
                ('plant_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plant_stats', to='pyflora_app.plant')),
                ('pot_senzors_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='pyflora_app.pot')),
            ],
            options={
                'ordering': ['-stats_time'],
                'get_latest_by': 'stats_time',
            },
        ),
    ]
